### PR TITLE
AUR publish actions: Remove checkingout of tag

### PR DESCRIPTION
**Pull request by ErikReider**
Realized that I wouldn't be able to sleep before this is fully fixed 😅

### CODE REVIEW

**Comment by WillPower3309** [comment]
Looks like the wrong link is still listed in the aur sources list unfortunately

**Comment by zoro11031** [comment]
I can confirm, AUR build spits a 404 error and quits 

`-> Downloading swayfx-0.1.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/WillPower3309/swayfx/releases/download/0.1/swayfx-0.1.tar.gz
    Aborting...
 -> error downloading sources: swayfx 
	context: exit status 1 
	

 -> meson not satisfied, flushing install queue`

**Comment by ErikReider** [comment]
I ran the action again and it actually worked!

**Comment by zoro11031** [comment]
Yep you were right! Just needed to run a cleanbuild! Awesome

**Comment by WillPower3309** [comment]
Thanks a ton! Announcement is up
https://www.reddit.com/r/unixporn/comments/yw3e5r/swayfx_introducing_swayfx_sway_but_with_fx/

**Comment by ErikReider** [comment]
> Thanks a ton! Announcement is up
> https://www.reddit.com/r/unixporn/comments/yw3e5r/swayfx_introducing_swayfx_sway_but_with_fx/

Already over 250 upvotes?! People seem to like these fancy effects!
Here's my post: https://www.reddit.com/r/unixporn/comments/yw8k9o/swayfx_i_hope_this_sways_your_opinion_on_wayland/
Couldn't resist the cheesy jokes...

**Pull request merged**
