### PR TITLE
feat: add checksum to PKGBUILD

### PR DESCRIPTION
**Pull request by harogaston**
I believe this should work to resolve https://github.com/WillPower3309/swayfx/issues/154 though I don't know how to test it locally. Uses https://github.com/marketplace/actions/publish-aur-package

### CODE REVIEW

**Comment by WillPower3309** [comment]
Hope you don't mind me requesting your review Erik! You have a lot more packaging experience than I

**Review by ErikReider — COMMENTED** [review]
Not sure but I think that we'd need to update our secrets to match the ones required for the new action?

We'd also need to update the PKGBUILD in our repo for this to work. An example would be https://github.com/sane-fmt/sane-fmt/blob/c07ce4f09c0b8dfa902d28753ebb3800268183f5/template/sane-fmt-bin/PKGBUILD which also uses this action

**Comment by ErikReider** [comment]
We should move this to https://github.com/wlrfx/aur-packages

**Comment by WillPower3309** [comment]
Closed as we no longer have package definitions in this repo

**Pull request closed without merging**
