### PR TITLE
Add rounded corners

### PR DESCRIPTION
**Pull request by WillPower3309**
Adds rounded corners
Current appearance:

### CODE REVIEW

**Comment by WillPower3309** [comment]
TODO:
+ default to not rounding the corner on certain ui elements (ie the top panel)
+ antialiasing

**Comment by WillPower3309** [comment]
TODO: Add rules to avoid rounding corners on certain windows and default to not rounding certain UI elements (inc panel)

**Comment by WillPower3309** [comment]
> TODO: Add rules to avoid rounding corners on certain windows and default to not rounding certain UI elements (inc panel)

Will ignore rounding on certain UI elements such as panels / background. Rules will be added in #10

**Comment by fluix-dev** [comment]
Hey, I'm the developer of [sway-borders](https://github.com/fluix-dev/sway-borders) which tries to achieve similar goals of this project (although it's been in the works for far too long without much progress). I recently pushed rounded corners to a beta branch and it includes anti-aliasing which I think you might like here.

https://github.com/fluix-dev/sway-borders/blob/9f1cfcfca44933f47991c267e44183c707732c37/sway/desktop/renderer.c#L30 (issue with screenshot: https://github.com/fluix-dev/sway-borders/issues/54#issuecomment-1213643711)

Happy to see another project improving on the looks of Sway, I might take a shot at making some PRs since I'm essentially rewriting sway-borders with a custom renderer too. Let me know if you want to work together more closely.

**Comment by WillPower3309** [comment]
Hey @fluix-dev, great work on sway-borders! Looks like we've got a lot of similar ideas with our renderer implementations, I'll definitely take a closer look at your anti-aliased shader. For now, I've just been ripping the shaders from Hyprland (which is part of what has allowed me to progress so quickly on this fork). I would absolutely like to work more closely on giving sway some more eye-candy!

**Comment by WillPower3309** [comment]
WIll need to adjust titlebar and border dawing

**Pull request merged**
