### PR TITLE
Official Copr repo

### PR DESCRIPTION
**Pull request by ErikReider**
Todo:

- [x] Copr GitHub Action
- [x] Fedora build action
- [x] Spec file
- [ ] ~Bump spec file version on release~

Copr setup todo:

- [x] Create account
- [x] Add `COPR_API_TOKEN` and `COPR_REPO_NAME` Actions secrets. Can be gotten from https://copr.fedorainfracloud.org/api/ while logged in. @WillPower3309 You may also need to enable GitHub Actions

Fixes: #28

### CODE REVIEW

**Comment by ErikReider** [comment]
Seems like automatically bumping the version is more complicated than anticipated so I'll scratch that from this PR

**Comment by WillPower3309** [comment]
Thanks a ton for getting this working! I'll figure out the account stuff later today

**Comment by WillPower3309** [comment]
Could something like this be done for #12 as well?

**Comment by ErikReider** [comment]
> Could something like this be done for #12 as well?

I'll look into it :)

**Comment by WillPower3309** [comment]
> > Could something like this be done for #12 as well?
> 
> I'll look into it :)

Absolute king

**Comment by WillPower3309** [comment]
Account and repo set up: https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/

I assume REPO_NAME is just `swayfx`? If so, the secrets are also good to go.

**Comment by WillPower3309** [comment]
I've left external repositories and runtime dependencies for the copr project repo empty for now, is this something that would need to be populated as well?

**Review by WillPower3309 — APPROVED** [review]

**Comment by ErikReider** [comment]
> I assume REPO_NAME is just `swayfx`? If so, the secrets are also good to go.

I think so? If not, it could be `swayfx/swayfx`?

> I've left external repositories and runtime dependencies for the copr project repo empty for now, is this something that would need to be populated as well?

I'll check rn

**Comment by ErikReider** [comment]
> I've left external repositories and runtime dependencies for the copr project repo empty for now, is this something that would need to be populated as well?

Should be fine without those filled in. All packages exists in the default Fedora repos :)

**Comment by WillPower3309** [comment]
Unfortunately it looks like the copr action is failing after releasing version 0.1. As a side note, would you mind testing the two arch packages?

**Comment by ErikReider** [comment]
> Unfortunately it looks like the copr action is failing after releasing version 0.1.

Working on it 🛠️

**Comment by ErikReider** [comment]
> Unfortunately it looks like the copr action is failing after releasing version 0.1. As a side note, would you mind testing the two arch packages?

Fixed by: #36

**Pull request merged**
