### PR TITLE
Implement Better Borders (incl rounded)

### PR DESCRIPTION
**Pull request by WillPower3309**
Based on https://www.shadertoy.com/view/st3BR8

TODO:
+ [ ] Add color config support
+ [x] Clean up the rest of the border config from render.c (look into state.border_thickness vs config->border_thickness)
+ [x] Move to a separate shader for rendering with decorations?
+ [ ] Could pass in the container as a param which would have border info and more to clean up the number of params (and likely make future blur work easier)
+ [ ] Fix sizing
+ [ ] Fix damage tracking
+ [x] Clean up rgba shader
+ [x] Update rgbx and ext shaders
+ [x] Fix border cut off
+ [ ] Look into fixing CSD issues (curse you and your poor design decisions gnome!)
+ [ ] Update border config options
+ [ ] Remove indicator stuff
+ [x] Remove hide_edge_borders
+ [ ] Look into show_marks config option
+ [ ] Ensure smart borders are supported

### CODE REVIEW

**Comment by WillPower3309** [comment]
As you can see, outer border radius needs some adjusting, however it blends with the main window perfectly due to being in the same shader now, I can use the mix() function

**Comment by WillPower3309** [comment]
The cool thing about this implementation is that render_rect can now be render_titlebar (since it won't be used for anything else anymore), and it can handle having rounded corners at the top without needing a separate shader specific to it.

**Comment by ErikReider** [comment]
Oh this is very interesting! I can try fixing some of the stuff :)

**Comment by ErikReider** [comment]
How does this affect popups? It uses the regular renderer right?

**Comment by ErikReider** [comment]
Seems like floating windows aren't clipped properly due to the GTK shadows
image
Maybe only apply to tiled windows or is there a fix?

**Comment by WillPower3309** [comment]
> How does this affect popups? It uses the regular renderer right?

Yup! Should function as expected

**Comment by WillPower3309** [comment]
> Seems like floating windows aren't clipped properly due to the GTK shadows
> image
> Maybe only apply to tiled windows or is there a fix?
> Or maybe clip everything outside of the application and use `state->content_height` / `state->content_width` instead

So right now, clipping is an issue we need to fix. I can guarantee that the shader itself works, it's just being clipped to the window area right now

**Comment by WillPower3309** [comment]
If you pull now, you'll likely find you can only see the corner of the border. This is intended! It will be fixed once clipping is done.

**Comment by WillPower3309** [comment]
Border cut off now fixed, should look as expected! Still need to fix CSD issues

**Comment by WillPower3309** [comment]
Picture for reference:

**Comment by WillPower3309** [comment]
At a conference this week but I'll aim to get this through the door before I fly back, should be able to get titlebars done on the flight and hopefully release 0.1 for the weekend!

**Comment by ErikReider** [comment]
Were you planing on adding the split indicator? You could always use the original indicator code (only render that rectangle if split in that direction), but that may come with some size inconsistencies...

**Comment by ErikReider** [comment]
> I was thinking it would be scrapped, depending on how common of a use case it is. Personally I prefer it without as the different colored side doesn't look great to me, but if it's a popular feature we could definitely keep it!

I use it with `autotiling` so it doesn't matter that much for me. It's just nice seeing if it needs to be toggled before opening a window but it can always be added in a future PR :)

**Comment by WillPower3309** [comment]
> > I was thinking it would be scrapped, depending on how common of a use case it is. Personally I prefer it without as the different colored side doesn't look great to me, but if it's a popular feature we could definitely keep it!
> 
> I use it with `autotiling` so it doesn't matter that much for me. It's just nice seeing if it needs to be toggled before opening a window but it can always be added in a future PR :)

Good to know! I think I'll leave it out of scope for now but raise an issue to bring it back when this is merged

**Comment by WillPower3309** [comment]
Now have separate shaders for rendering with effects. This will allow undecorated textures to render as fast as possible, at the cost of higher complexity. I'll work on refactoring it to be as clear as possible

**Comment by WillPower3309** [comment]
This is proving to be a very difficult problem. I'm still actively working on it, but haven't had any findings worth presenting.

Essentially we need to know the color of the border and of the texture it's going around to blend the two colors at the corners to avoid the issues with the gap between the corner border and corner of the window. Unfortunately, I'm having a hard time actually getting the border to render without cutting into the window texture, since it doesn't want to render anything outside of the area that the window encompasses.

**Comment by ErikReider** [comment]
> it doesn't want to render anything outside of the area that the window encompasses.

I've noticed that dragging the window in floating mode results in a weird effect that I can't really describe with words. I haven't checked your code yet but wouldn't allocating more width and height fix this?

**Comment by WillPower3309** [comment]
> > it doesn't want to render anything outside of the area that the window encompasses.
> 
> I've noticed that dragging the window in floating mode results in a weird effect that I can't really describe with words. I haven't checked your code yet but wouldn't allocating more width and height fix this?
> 
> 

Yup, thats related to the issues with damage tracking (which are related to the issues of rendering outside of the window region). I've tried to make a lot of adjustments to width / height but I'm facing an issue where these changes make the window texture also resize. As an example, while changing the size / position allows the borders to be rendered, it also resizes the window texture which results in the borders rendering over the window. This can be seen in the screenshot I sent earlier (although it may be hard to tell)

**Comment by WillPower3309** [comment]
Related: https://github.com/yilozt/rounded-window-corners

Seems to handle the gtk CSD shadows as well

**Comment by WillPower3309** [comment]
Current appearance (for reference in the stackoverflow thread I'm creating xD ):

**Comment by WillPower3309** [comment]
Closed in favor of #22

**Pull request closed without merging**
