### PR TITLE
Fix layer surface damage not being extended if using effects

### PR DESCRIPTION
**Pull request by ErikReider**

### CODE REVIEW

**Comment by ErikReider** [comment]
Undoing the marking as draft, found a damage bug but it's there for upstream as well

**Comment by WillPower3309** [comment]
> Undoing the marking as draft, found a damage bug but it's there for upstream as well

What's the bug? :S

**Review by WillPower3309 — APPROVED** [review]

**Comment by ErikReider** [comment]
Oh. Forgot to mention the actual bug 😅

The shadows would render once and be clipped in some circumstances. Also blur needs to have the extended damage for layers above so that we don't get those pesky clipped blur artifacts.

An example would be opening rofi with shadows enabled. I'm not at my PC atm, so can't send a screenshot

**Comment by ErikReider** [comment]
> > Undoing the marking as draft, found a damage bug but it's there for upstream as well
> 
> What's the bug? :S

Here's the [pr](https://github.com/swaywm/sway/pull/7597) :)

**Comment by WillPower3309** [comment]
Oh upstream! Perfect

**Pull request merged**
