### PR TITLE
1.9 merge

### PR DESCRIPTION
**Pull request by fishman**
render layoer_shell, render, and seatop_move_tiling and fx_renderer are currentlyt he main things that seem to require major changes.

### CODE REVIEW

**Comment by WillPower3309** [comment]
Thanks for the work here! We'd like to use the 1.9 release to transition our fx_renderer to use the fx_renderer we've built in [scenefx](https://github.com/wlrfx/scenefx), which will have feature parity with the fx_renderer bundled in swayfx. As part of that, we will simply just have to import fx_renderer from scenefx and it should be plug and play for that portion of the rebase.

**Comment by WillPower3309** [comment]
I'm going to make a few additions to this branch to move along some of the WIP parts, I hope you don't mind :)

**Comment by WillPower3309** [comment]
Should just be render.c that needs fixing now

**Comment by WillPower3309** [comment]
Relies on the `swayfx-compat` scenefx branch

**Comment by WillPower3309** [comment]
right now it is sort of functional but black screens a lot with
```
00:00:19.617 [wlr] [render/swapchain.c:98] No free output buffer slot
```

**Comment by WillPower3309** [comment]
Once the buffer slot issue is fixed, we can start adding back some of the eye candy (lots of TODOs)

**Comment by ErikReider** [comment]
Seems like there's a lot of missing code from sway 1.9, like the root.c file not compiling without manually copy/pasting the contents from sway 1.9

**Comment by ErikReider** [comment]
Not sure if the rebase was applied correctly :/

**Comment by WillPower3309** [comment]
All that's left now are adding back the compositor effects in render.c (see the many TODOs), and scenefx

**Comment by ErikReider** [comment]
Shadow offset and blur is now in :)

**Comment by ErikReider** [comment]
So this is what's left (feel free to edit this comment with additional features that I've missed):
- [ ] Expose fx_renderer as public?
- [ ] Window corners
- [ ] Rounded rects
- [ ] Border corners
- [ ] Titlebar bottom broder compensation

**Comment by WillPower3309** [comment]
> So this is what's left (feel free to edit this comment with additional features that I've missed):
> - [ ] Expose fx_renderer as public?
> - [ ] Window corners
> - [ ] Rounded rects
> - [ ] Border corners
> - [ ] Titlebar bottom broder compensation

Yup! I think we already expose the renderer as part of the scenefx branch. We should also test everything scaled + rotated.

**Comment by WillPower3309** [comment]
The bottom border compensation works but also applies when it shouldn't. Will fix tomorrow

**Comment by WillPower3309** [comment]
scaled shadow damage tracking is broken

**Comment by WillPower3309** [comment]
While it would be best to hide the fx_renderer implementation details, we will likely need to expose fx_renderer as public before scene is ready

**Comment by WillPower3309** [comment]
I'm not opposed to backporting scene changes from mainline sway to swayfx early

**Comment by WillPower3309** [comment]
also need to discuss dimming + saturation. Personally I am starting to think we should deprecate saturation

**Comment by ErikReider** [comment]
> Personally I am starting to think we should deprecate saturation

Agreed! Not really that useful due to direct scanout needing to be disabled

**Comment by WillPower3309** [comment]
> Was there a feature for using custom shaders? If so, that would supersede custom saturation, wouldn't it?

Yup! We have an open issue for it, but don't have an implementation yet. It would be possible to get saturation with custom shaders, but wouldn't work on Fullscreen windows due to direct scan out

**Comment by WillPower3309** [comment]
titlebars mostly done, need to properly render the border corners and the tabbed edge container titlebars

**Comment by WillPower3309** [comment]
ok! All that is left is scaled + rotated effects. Right now there are a couple issues on the scenefx side that I have called out in that PR as well

**Comment by WillPower3309** [comment]
Shadow scaling mostly fixed, some weird effects between windows evident:

**Comment by WillPower3309** [comment]
More fine grained TODO:
+ [] Rotated blur
+ [] Scaled shadows
+ [] Blur cropping on windows w CSD (tracked in https://github.com/wlrfx/scenefx/pull/35)

**Comment by WillPower3309** [comment]
Found another issue, when moving a floating window the bottom border can be 1 px off in some positions - likely a rounding issue

**Comment by WillPower3309** [comment]
We need to have a discussion on if we should keep scaling in the scene side or make it a compositor responsibility

**Comment by WillPower3309** [comment]
Annoying shadow issue when there are no borders (1px wide black "border" between window and shadow, stencil issue?):

**Comment by ErikReider** [comment]
> Annoying shadow issue when there are no borders (1px wide black "border" between window and shadow, stencil issue?): 

Narrowed it down to the stencil acting up. Very strange since we're using the same logic in master 🥴

**Comment by WillPower3309** [comment]
> > Annoying shadow issue when there are no borders (1px wide black "border" between window and shadow, stencil issue?): 
> 
> Narrowed it down to the stencil smoothstep function acting up. Very strange since we're using the same logic in master 🥴
> 
> Edit: Nvm, seems to be present in master as well, so it's at least not a regression :)

Ugh hopefully it'll be fixed once we switch to a matte

**Comment by WillPower3309** [comment]
With that in mind I think we have feature parity with upstream swayfx now, @ErikReider do you mind giving the render logic another look through? I'll do the same before merging

**Comment by OriginCode** [comment]
Maybe a little bit off-topic, but will scenefx be tagged soon after or before this PR is merged? It will help a lot for distribution packagers.

**Comment by WillPower3309** [comment]
> Maybe a little bit off-topic, but will scenefx be tagged soon after or before this PR is merged? It will help a lot for distribution packagers.

Yup! As soon as the corresponding scene PR is merged I will tag a release

**Review by WillPower3309 — APPROVED** [review]

**Pull request merged**
