### PR TITLE
per container border colors 

### PR DESCRIPTION
**Pull request by rohansukhdeo**
https://github.com/michaelweiser/sway/tree/window-colours

this is sway fork with the per container border colors implemented in two commits 

This only allows seat 0 to change border colors, but we would also like per seat per container border colors optionality, meaning that when seat 2 is the latest seat to focus on a given window, it automatically "marks" this container as owned by seat 2, that way if specified in the sway config it lets you change the color of the container when highlighted

### CODE REVIEW

**Comment by WillPower3309** [comment]
Thanks a ton Rohan, we'll take a look at this once #78 is merged. That should clean up the diff a bit to just the border changes

**Comment by rohansukhdeo** [comment]
Great thank you! I also have an APKBUILD Script that you can use that build an apk package for this for alpine linux. Let me know and I could send that over!

**Comment by WillPower3309** [comment]
> Great thank you! I also have an APKBUILD Script that you can use that build an apk package for this for alpine linux. Let me know and I could send that over!

That would be awesome!

**Comment by rohansukhdeo** [comment]
https://github.com/enoki-inc/alpine-package-sway-aither

here is the repo, just made it public

includes instructions and everything required to build the APKBUILD script

**Comment by WillPower3309** [comment]
> https://github.com/enoki-inc/alpine-package-sway-aither
> 
> here is the repo, just made it public
> 
> includes instructions and everything required to build the APKBUILD script

Awesome, I'll tag our auto build specialist @ErikReider here, if he's got too much on his plate ik happy to set it up here too!

**Comment by rohansukhdeo** [comment]
great!

**Comment by ErikReider** [comment]
> Awesome, I'll tag our auto build specialist @ErikReider here, if he's got too much on his plate I'm happy to set it up here too!

I'm not sure how much time I'll have this week but I'll try to look into it after I've squashed some bugs :)

**Comment by ErikReider** [comment]
Rebase from master?

**Comment by ErikReider** [comment]
> Great thank you! I also have an APKBUILD Script that you can use that build an apk package for this for alpine linux. Let me know and I could send that over!

Build and redistribute the build package in each release or for testing if it builds on Alpine?

**Comment by WillPower3309** [comment]
> Rebase from master?

Make sure you're tracking SwayFX as well and not sway, we've recently pulled in the 1.8 changes

**Comment by WillPower3309** [comment]
> Rebase from master?

Make sure you're tracking SwayFX as well and not sway, we've recently pulled in the 1.8 changes

**Comment by rohansukhdeo** [comment]
yeah if you could build and redistribute in each release that'd be great!

also I'm curious, do you guys have a build script for ubuntu?

**Pull request closed without merging**
