### PR TITLE
Add Anti-Aliased Corner Radius

### PR DESCRIPTION
**Pull request by WillPower3309**
Before:

After:

### CODE REVIEW

**Comment by WillPower3309** [comment]
I realized I have a transparent terminal in the "After". I promise it looks equally AA-ed without the transparency. Some of the corners of the AA-ed window seem off to me though, will look over prior to merging.

**Comment by WillPower3309** [comment]
Appearance fixed, will add shaders for rgbx and ext then merge

**Comment by ErikReider** [comment]
Looks really good! :)

**Comment by ErikReider** [comment]
Hmmm. Seems like Webcord, Discord, Spotify do not work. I'll test the main branch and see if it's reproducible there.

Edit: seems like the main branch works

**Comment by WillPower3309** [comment]
Ah, do they just render sharp corners? If so I know what the issue is, and it's the reason I haven't merged this yet! Right now I still need to add aa-ed shaders for a couple texture types which I assume encompasses those applications

**Comment by WillPower3309** [comment]
> Hmmm. Seems like Webcord, Discord, Spotify do not work. I'll test the main branch and see if it's reproducible there.
> 
> Edit: seems like the main branch works

Check now, it should work! If it does I'll merge this PR

**Comment by ErikReider** [comment]
Hmmm, works but there's no transparency for those windows:
image

**Comment by WillPower3309** [comment]
> Hmmm, works but there's no transparency for those windows:
> image
> 
> Always enabling `GL_BLEND` fixes the issue but does it have a performance cost?

Good to know! I'll look into it further

**Comment by WillPower3309** [comment]
So a couple things to note: the wlr_renderer explicitly turns blending off on texture formats that aren't rgba and don't have an alpha < 1, and explicitly turns blending on otherwise. Hyprland instead always has blending on for rendering subtextures. This is making me think if we want AA we may need to enable it, because otherwise we'd just be discarding instead which is what the prior implementation used without AA. Ill look into this further, but those are the current findings.

**Pull request merged**
