### PR TITLE
Move to wlr_buffer and wlr_texture

### PR DESCRIPTION
**Pull request by ErikReider**
This will make it easier for us to rebase on top of the upcoming sway 1.9 release

### CODE REVIEW

**Comment by WillPower3309** [comment]
might be a bit confused - I thought the goal here was to move to wlr_texture and wlr_buffer but it looks like we still use the fx counterparts?

**Comment by ErikReider** [comment]
> might be a bit confused - I thought the goal here was to move to wlr_texture and wlr_buffer but it looks like we still use the fx counterparts?

My understanding is that those structs are generic so that others can implement their own buffers/textures. Wlroots creates `wlr_gles2_texture` and `wlr_gles2_buffer` and use those internally for their gles2 backend

**Comment by WillPower3309** [comment]
might be a bit confused - I thought the goal here was to move to wlr_texture and wlr_buffer but it looks like we still use the fx counterparts?

**Comment by ErikReider** [comment]
But I just realized that it doesn't build at the moment due to wlroots not providing the swaychain.h header unless it's a submodule -_-

**Pull request closed without merging**
