### PR TITLE
Added flake support for wlroots subproject

### PR DESCRIPTION
**Pull request by JavaCafe01**
@WillPower3309 devshell should work for the wlroots subproject now.

### CODE REVIEW

**Comment by JavaCafe01** [comment]
On a whole another note, is there an easier way to communicate? Like a swayfx matrix/discord?

**Comment by WillPower3309** [comment]
Works perfectly, thanks a ton!

**Comment by WillPower3309** [comment]
> On a whole another note, is there an easier way to communicate? Like a swayfx matrix/discord?

This is a really good idea! Ill set one up and ping you and Erik + update the README

**Comment by ErikReider** [comment]
> This is a really good idea! Ill set one up and ping you and Erik + update the README

Cool! This would be great :)

Have a good Turkey day! 🦃

**Comment by WillPower3309** [comment]
https://discord.gg/jVjjFdcN

@JavaCafe01 @ErikReider

**Pull request merged**
