### PR TITLE
Added chimera linux support 

### PR DESCRIPTION
**Pull request by Bikoil**
**Heya!** i added chimera linux support for this by making it check for chimera's wlroots package, this is due to the naming of the wlroots package in chimera, so when it searches for `wlroots` and doesnt find it, it will try again searching for `wlroots-0.17` which is the one for chimera.

This is a bit related to [this scenefx issue](https://github.com/wlrfx/scenefx/issues/58), and i might open another pull request in scenefx for chimera linux support too! thanks.

### CODE REVIEW

**Comment by ErikReider** [comment]
How does upstream handle this? Is this an issue there as well?

**Comment by Bikoil** [comment]
> How does upstream handle this? Is this an issue there as well?

Basically, it checks for `wlroots` with pkgconf, if wlroots wasn't found anywhere in the system, it will go over check for `wlroots-0.17`, which is how chimera linux names wlroots for some reason, so it finds it and uses it... and if it doesnt find it either it will look in `subprojects`

Also yes! this is an issue there too, since swayfx and scenefx both look for the same `wlroots` name, both of them will fail to compile in chimera automatically.

Btw i did try to make it so it looks for `wlroots-{wlroots version variable}` but i didnt know how to exactly do it :sweat_smile:

**Comment by WillPower3309** [comment]
Hey @Bikoil huge thanks for looking into this. I had a suspicion that chimera linux may provide this as a patch, and it looks like my hunch was correct! https://github.com/chimera-linux/cports/blob/master/main/sway/patches/versioned-wlr.patch

If you could instead implement this as a patch, I think it would be better to live on the chimera package side, so that we don't need to update it every time we increment the wlroots version

**Comment by WillPower3309** [comment]
The entire package definition is here: https://github.com/chimera-linux/cports/tree/master/main/sway

**Comment by Bikoil** [comment]
Thank you Will, I'll add the patch file from the sway package right when I can, For now, I'll close the pull requests since they won't be used :)

**Pull request closed without merging**
