### PR TITLE
Fixed PKGBUILD stable not downloading, building and packaging

### PR DESCRIPTION
**Pull request by ErikReider**
#35

Second try's the charm!

### CODE REVIEW

**Comment by ErikReider** [comment]
Running both actions locally with act:

- arch-build-stable: ✅  Success - Main Stable makepkg build and check
- arch-build-git: ✅  Success - Main Git makepkg build and check
- aur-publish-stable: ✅  Kinda success (getting error message due to me not having the correct ssh key)
- aur-publish-git: ✅  Kinda success (getting error message due to me not having the correct ssh key)

**Comment by ErikReider** [comment]
Every thing should™ work now including the new #41 PR. Thanks for being so patient :)

**Comment by ErikReider** [comment]
Got a small heart attack when I read the email about the Action failing. I was ready for an all-nighter!

**Comment by WillPower3309** [comment]
Great work, both actions are now passing! It does appear though that https://aur.archlinux.org/packages/swayfx still displays the old source, which is strange considering the action seemed to work correctly

**Comment by ErikReider** [comment]
> It does appear though that https://aur.archlinux.org/packages/swayfx still displays the old source, which is strange considering the action seemed to work correctly

Spoke too soon... Seems like the action published an empty commit. I'll look into it tomorrow

**Comment by WillPower3309** [comment]
> > It does appear though that https://aur.archlinux.org/packages/swayfx still displays the old source, which is strange considering the action seemed to work correctly
> 
> Spoke too soon... Seems like the action published an empty commit. I'll look into it tomorrow

no worries. I'll plan a release announcement for tomorrow afternoon!

**Comment by ErikReider** [comment]
> I'll plan a release announcement for tomorrow afternoon!

What timezone? I'm also planing to post but I wanna do it after the initial announcement! :)

**Comment by WillPower3309** [comment]
> > I'll plan a release announcement for tomorrow afternoon!
> 
> What timezone? I'm also planing to post but I wanna do it after the initial announcement! :)

Awesome! I'm in EST, was planning on a noon announcement

**Pull request merged**
