### PR TITLE
Add AUR publish and Arch build GitHub Actions

### PR DESCRIPTION
**Pull request by ErikReider**
Fixes: #12 

@WillPower3309 You'll need to create a AUR repo before this is usable.

Steps (more info [here](https://wiki.archlinux.org/title/AUR_submission_guidelines) in case I've forgotten something):

1. Create AUR account and insert a public ssh key
2. Run to create the repo (won't publish until you run): `git clone ssh://aur@aur.archlinux.org/swayfx.git`
3. Run: `git remote add origin ssh://aur@aur.archlinux.org/swayfx.git`
4. Copy the PKGBUILD, `50-systemd-user.conf`, and `sway.install` from `build-scripts/aur` into the AUR repo
5. Run `makepkg --printsrcinfo > .SRCINFO` (I'm not sure if `makepkg` is available on NixOS)
6. Git add, commit and push to create the repo
7. Add your ssh key into a GitHub Actions variable called `AUR_SSH_PRIVATE_KEY`

Todo:

- [x] Action should update `50-systemd-user.conf` and `sway.install`
- [x] Publish action on every release
- [x] Checkout latest tag instead of master
- [x] Test build action to run on each commit

*Note:* Does not include auto version updating

### CODE REVIEW

**Comment by ErikReider** [comment]
How are you @WillPower3309 planning to name each release and tag? I've got a weird idea...

Instead of needing to update every package file manually, we could read the version from a `VERSION` file, or maybe even from the `meson.build`?

**Comment by ErikReider** [comment]
Update: With the new addon you'll need to add `AUR_USERNAME` and `AUR_EMAIL` to secrets

**Comment by WillPower3309** [comment]
Is this ready to be merged?

**Comment by ErikReider** [comment]
I'll have to double check everything tomorrow. It's currently 3 AM here so I don't really trust my eyes right now :O

**Comment by WillPower3309** [comment]
> I'll have to double check everything tomorrow. It's currently 3 AM here so I don't really trust my eyes right now :O

Oh you're quite a few hours ahead of me then! Sounds good, we can get a release out tomorrow

**Comment by ErikReider** [comment]
It also seems like GitHub Actions aren't running after commits? The Fedora build one should run on every commit

**Comment by WillPower3309** [comment]
Hmm very strange, I'll look into this

**Comment by ErikReider** [comment]
I've changed the AUR and the COPR actions to checkout the latest tag instead of cloning from master so the actions can easily be re-run in case of a failiure :)

**Review by WillPower3309 — APPROVED** [review]
LGTM!

**Comment by WillPower3309** [comment]
Quick question - do the two build scripts update the packages on commit? If so, the package should be named `swayfx-git`

**Comment by WillPower3309** [comment]
We can keep `swayfx` for releases (which would provide a more stable option)

**Comment by ErikReider** [comment]
> Quick question - do the two build scripts update the packages on commit? If so, the package should be named `swayfx-git`

The one provided goes by release. I can create one that does off of commit

**Comment by ErikReider** [comment]
Everything done on my end. Now the only thing left is to enable GitHub Actions in the projects Actions settings and add those Actions secrets

**Comment by WillPower3309** [comment]
Awesome! On release is good for now, I'll enable those and get this rolled out!

**Comment by WillPower3309** [comment]
Looks like the source on the [AUR page](https://aur.archlinux.org/packages/swayfx) (https://github.com/WillPower3309/swayfx/releases/download/0.1/swayfx-0.1.tar.gz) is dead. Could be updated to https://github.com/WillPower3309/swayfx/archive/refs/tags/0.1.tar.gz?

**Comment by ErikReider** [comment]
> Looks like the source on the [AUR page](https://aur.archlinux.org/packages/swayfx) (https://github.com/WillPower3309/swayfx/releases/download/0.1/swayfx-0.1.tar.gz) is dead. Could be updated to https://github.com/WillPower3309/swayfx/archive/refs/tags/0.1.tar.gz?

Fixed by: #35

**Pull request merged**
